float32[6]    point
float32       speed
float32       acceleration
float32       time_for_waiting_start  # maximum duration (in seconds) to wait for start signal before timing out.
---
bool          success
---
SystemState   state